# path: aida/config.yml
# title: Application Configuration
# role: Provides configuration settings for the AIDA application.

llm:
  provider: "ollama"
  model: "gemma3:latest"
  host: "http://localhost:11434"

rag:
  embedding_model: "nomic-embed-text:latest" # Ollamaで実行する埋め込みモデル名
  chunk_size: 1000
  chunk_overlap: 200

web_search:
  google_api_key: ""
  google_cse_id: ""
  
max_retries: 5
